### ISSUE TITLE
SDK 5.5.1 Crash

### ISSUE THREAD

**Issue by iOSDevFin** [appnexus/mobile-sdk-ios#45] opened 2019-08-19 12:10 UTC
Hi,

I have successfully integrated AppNexus in my app. However, on my first controller everything is working fine loading the ads including an interstitial as well. Once I navigate on a second controller and doing the same stuff there (ne instance of ANBannerAdView) I always get a crash with the following stack trace. 

The strange thing is, when I remove the ads from the first controller, the second controller is working fine.

Any ideas what this issue below could cause from your perspective? I can not post detailled code due to company sla's

Many thanks,
Maik

2019-08-19 13:59:54.361798+0200 App[35477:8092844] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid number value (infinite) in JSON write'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010feb46fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010f458ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010feb4555 +[NSException raise:format:] + 197
	3   Foundation                          0x0000000109be4b78 _writeJSONNumber + 547
	4   Foundation                          0x0000000109be1a69 _writeJSONValue + 495
	5   Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	6   CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	7   Foundation                          0x0000000109be5046 _writeJSONObject + 466
	8   Foundation                          0x0000000109be5c7f ___writeJSONArray_block_invoke + 130
	9   CoreFoundation                      0x000000010fddff0c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	10  Foundation                          0x0000000109be54ba _writeJSONArray + 300
	11  Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	12  CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	13  Foundation                          0x0000000109be5046 _writeJSONObject + 466
	14  Foundation                          0x0000000109be5c7f ___writeJSONArray_block_invoke + 130
	15  CoreFoundation                      0x000000010fddff0c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	16  Foundation                          0x0000000109be54ba _writeJSONArray + 300
	17  Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	18  CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	19  Foundation                          0x0000000109be5046 _writeJSONObject + 466
	20  Foundation                          0x0000000109be5c7f ___writeJSONArray_block_invoke + 130
	21  CoreFoundation                      0x000000010fddff0c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	22  Foundation                          0x0000000109be54ba _writeJSONArray + 300
	23  Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	24  CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	25  Foundation                          0x0000000109be5046 _writeJSONObject + 466
	26  Foundation                          0x0000000109be5c7f ___writeJSONArray_block_invoke + 130
	27  CoreFoundation                      0x000000010fddff0c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	28  Foundation                          0x0000000109be54ba _writeJSONArray + 300
	29  Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	30  CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	31  Foundation                          0x0000000109be5046 _writeJSONObject + 466
	32  Foundation                          0x0000000109be5c7f ___writeJSONArray_block_invoke + 130
	33  CoreFoundation                      0x000000010fddff0c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	34  Foundation                          0x0000000109be54ba _writeJSONArray + 300
	35  Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	36  CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	37  Foundation                          0x0000000109be5046 _writeJSONObject + 466
	38  Foundation                          0x0000000109be5c7f ___writeJSONArray_block_invoke + 130
	39  CoreFoundation                      0x000000010fddff0c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	40  Foundation                          0x0000000109be54ba _writeJSONArray + 300
	41  Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	42  CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	43  Foundation                          0x0000000109be5046 _writeJSONObject + 466
	44  Foundation                          0x0000000109be5c7f ___writeJSONArray_block_invoke + 130
	45  CoreFoundation                      0x000000010fddff0c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	46  Foundation                          0x0000000109be54ba _writeJSONArray + 300
	47  Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	48  CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	49  Foundation                          0x0000000109be5046 _writeJSONObject + 466
	50  Foundation                          0x0000000109be5c7f ___writeJSONArray_block_invoke + 130
	51  CoreFoundation                      0x000000010fddff0c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	52  Foundation                          0x0000000109be54ba _writeJSONArray + 300
	53  Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	54  CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	55  Foundation                          0x0000000109be5046 _writeJSONObject + 466
	56  Foundation                          0x0000000109be5c7f ___writeJSONArray_block_invoke + 130
	57  CoreFoundation                      0x000000010fddff0c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	58  Foundation                          0x0000000109be54ba _writeJSONArray + 300
	59  Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	60  CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	61  Foundation                          0x0000000109be5046 _writeJSONObject + 466
	62  Foundation                          0x0000000109be5c7f ___writeJSONArray_block_invoke + 130
	63  CoreFoundation                      0x000000010fddff0c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	64  Foundation                          0x0000000109be54ba _writeJSONArray + 300
	65  Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	66  CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	67  Foundation                          0x0000000109be5046 _writeJSONObject + 466
	68  Foundation                          0x0000000109be5c7f ___writeJSONArray_block_invoke + 130
	69  CoreFoundation                      0x000000010fddff0c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	70  Foundation                          0x0000000109be54ba _writeJSONArray + 300
	71  Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	72  CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	73  Foundation                          0x0000000109be5046 _writeJSONObject + 466
	74  Foundation                          0x0000000109be5c7f ___writeJSONArray_block_invoke + 130
	75  CoreFoundation                      0x000000010fddff0c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	76  Foundation                          0x0000000109be54ba _writeJSONArray + 300
	77  Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	78  CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	79  Foundation                          0x0000000109be5046 _writeJSONObject + 466
	80  Foundation                          0x0000000109be5c7f ___writeJSONArray_block_invoke + 130
	81  CoreFoundation                      0x000000010fddff0c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	82  Foundation                          0x0000000109be54ba _writeJSONArray + 300
	83  Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	84  CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	85  Foundation                          0x0000000109be5046 _writeJSONObject + 466
	86  Foundation                          0x0000000109be5c7f ___writeJSONArray_block_invoke + 130
	87  CoreFoundation                      0x000000010fddff0c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	88  Foundation                          0x0000000109be54ba _writeJSONArray + 300
	89  Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	90  CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	91  Foundation                          0x0000000109be5046 _writeJSONObject + 466
	92  Foundation                          0x0000000109be5c7f ___writeJSONArray_block_invoke + 130
	93  CoreFoundation                      0x000000010fddff0c -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 220
	94  Foundation                          0x0000000109be54ba _writeJSONArray + 300
	95  Foundation                          0x0000000109be5a98 ___writeJSONObject_block_invoke + 176
	96  CoreFoundation                      0x000000010ff249c2 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
	97  Foundation                          0x0000000109be5046 _writeJSONObject + 466
	98  Foundation                          0x0000000109be1826 -[_NSJSONWriter dataWithRootObject:options:error:] + 124
	99  Foundation                          0x0000000109be43b7 +[NSJSONSerialization dataWithJSONObject:options:error:] + 337
	100 AppNexusSDK                         0x00000001072ecc46 +[OMIDAppnexusDictionaryUtil stringFromJSON:] + 54
	101 AppNexusSDK                         0x00000001072f4cb7 __64-[OMIDAppnexusStatePublisher publishState:toSessions:timestamp:]_block_invoke + 115
	102 libdispatch.dylib                   0x00000001111f2d7f _dispatch_call_block_and_release + 12
	103 libdispatch.dylib                   0x00000001111f3db5 _dispatch_client_callout + 8
	104 libdispatch.dylib                   0x00000001111fb225 _dispatch_lane_serial_drain + 778
	105 libdispatch.dylib                   0x00000001111fbe9c _dispatch_lane_invoke + 425
	106 libdispatch.dylib                   0x0000000111205ea3 _dispatch_workloop_worker_thread + 733
	107 libsystem_pthread.dylib             0x00000001115a6611 _pthread_wqthread + 421
	108 libsystem_pthread.dylib             0x00000001115a63fd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by iOSDevFin** [comment] 2019-08-19 13:31
Some more news from investigation. We are using moya for our general network requests. For some reason our charting engine where we load our chart data is causing the crash when AppNexus is enabled. It looks like AppNexus is interfering with the json request somehow as it is listed in the stack trace.

When we just disable the AppNexus SDK, everything is working as expected. 

Looking forward hearing from you soon.

**Comment by Kowshickkarthick** [comment] 2019-08-19 15:24
Hi @iOSDevFin 

The crashes seem to originate from OMID SDK(Open Measurement) that ships with AppNexusSDK.
I would recommend turning off just OMID by using the below API.Doing this will run AppNexusSDK without OMID.(Viewability will fallback to MRAID) 

ANSDKSettings.sharedInstance().enableOpenMeasurement = false;

In the mean time we will try to reproduce the issue at our end and see if we can fix this and/or take it up with OMID team and get this fixed.

**Comment by iOSDevFin** [comment] 2019-08-20 07:16
Thank you! This fixed the issue for now. If you need any further details from me, let me know. I will ask my product management team to get in contact with their respective AppNexus managers to get this sorted out as we need proper viewability measurements going forward. I don't know yet which impact this mraid viewability has exactly.

**Comment by avermaiOS** [comment] 2019-08-30 14:55
Hi @iOSDevFin 

We tried to replicate the crash using the steps below :-
1. Created a sample app in Swift(v5) and integrated AppNexusSDK with Moya library (v13.0) via Cocoapods
2. Then created two UIViewControllers. On first controller, we made the banner ad request along with API request (fetching repositories) using Moya
3. Then moved to second controller without removing the ads from the first controller and repeat step 2
But didn't observe the crash when OMID SDK was enabled.

However, we were unable to replicate the crash.
Can you share a sample app/code that will help us reproduce this issue?

**Comment by iOSDevFin** [comment] 2019-09-03 07:11
Hi,

we've tested this internally as well and found out that our chart library shinobicharts is causing the issue when this is initialized on a viewcontroller change where AppNexus with OMID is used as well. We are using version 2.9.6-1 of shinobicharts which is not the current version but we can not update to the latest one.
It looks like a timing issue as when we delay initializing the chart, it works as well. But this is not a serious solution for our customers.
It would be great to know why the OMID SDK is crashing there, what is the OMID SDK doing what the chart is doing as well or do they both rely on react on json data beeing fetched or listened over the same technique? Why is AppNexus hooking up there and crashing?

I will try to create a little sample but don't know yet if I can reproduce it there as well.

Many thank

**Comment by Kowshickkarthick** [comment] 2019-12-04 16:09
HI @iOSDevFin 

We are still waiting on a reproduction case for this issue.
Unfortunately we won't be able to move forward on this sans a reproduction case.
I am closing this ticket, since there has been no update on it for a long time.

If this issue is still important and needs to be fixed, please visit the AppNexus Customer Support Portal (https://support.appnexus.com) and raise an issue. This will help us to track and resolve issues better.

Thanks 
Kowshick

**Closed by Kowshickkarthick** 2019-12-04 16:09 UTC
