### ISSUE TITLE
High CPU Load on OMIDAppnexusStatePublisher

### ISSUE THREAD

**Issue by danielerne** [appnexus/mobile-sdk-ios#57] opened 2020-10-28 14:35 UTC
Our App is getting warm on idle usage if we show AdBanners using AppNexus. If we profile it with Instruments we are getting high time load on [OMIDAppnexusStatePublisher publishState:toSessions:timestamp:container:]

For what is this function? Is it possible to optimize it?

We are using AppNexusSDK 7.7.1.

<img width="558" alt="OMIDAppnexusStatePublisher" src="https://user-images.githubusercontent.com/546931/97450518-1ddd4900-1933-11eb-9ad4-36cdb2abc601.png">

**Comment by ppuviarasu** [comment] 2020-11-04 21:39
hey @danielerne,

I am able to reproduce the stagger of the app after 5mins of using the app

I want to check if the stagger happened only after enabling the OMID or even before?
Also only on iOS 14 & not before?

**Comment by ivanlisovyi** [comment] 2020-12-10 15:14
@asharmaa Excuse me for direct mention but this is a very big issue and makes the apps unusable after just a few interactions with AppNexus banners, would it be possible for you guys to provide a bit more info on it?

**Comment by ppuviarasu** [comment] 2020-12-14 18:24
@ivanlisovyi we have worked on this & have raised an issue with IAB for the same. The team has acknowledged the issue and working on a fix. But we don't have a time frame for the same. 
Please create a case ticket so we can help you further on this

**Comment by s-hintz** [comment] 2021-01-19 13:37
What is the status of the IAB ticket?

**Comment by ppuviarasu** [comment] 2021-04-02 14:37
Hi @danielerne I dont have an answer from IAB. But trying to see if updating the OM SDK would help. Need some information on the view.
How long was the view live?
How many banners do you have on the view?
Does the banners refresh?
What was the action performed on the page? was it scrolling up & down or leaving the page idle for a long time.

**Comment by ppuviarasu** [comment] 2021-04-28 23:34
@danielerne, We have made some improvements to the OM SDK integration on our SDK. Can you update to the latest version of SDK v7.13 & confirm if you are still facing the issue mentioned?

Note : We still have few tickets pending with IAB that we are waiting for answers from them.

**Comment by danielerne** [comment] 2021-04-29 06:20
@ppuviarasu Thanks. I will check it today and let you know.

**Comment by danielerne** [comment] 2021-04-29 14:02
@ppuviarasu  The problem still exist. The app is idle but it requires a lot of cpu. 
<img width="1660" alt="cpu_load" src="https://user-images.githubusercontent.com/546931/116563376-435c0700-a904-11eb-9cf0-29b879decf4f.png">

**Comment by danielerne** [comment] 2021-04-29 14:06
> Hi @danielerne I dont have an answer from IAB. But trying to see if updating the OM SDK would help. Need some information on the view.
> How long was the view live?
> How many adslots do you have on the view?
> Does the banners refresh?
> What was the action performed on the page? was it scrolling up & down or leaving the page idle for a long time.

It occurs after first ad is display. So in a few seconds.
It displays in a UICollectionView. 3-5 Ads
Refresh yes
First scrolling up and down and after leaving idle

**Comment by ppuviarasu** [comment] 2021-04-29 14:27
HI @danielerne thanks for testing this quickly. I need another help
Can you open safari debug & check if there are multiple omid.js added when the app is idle?

**Comment by danielerne** [comment] 2021-04-29 15:38
@ppuviarasu As I can see there's only one script which has something  to do with omid
<img width="1422" alt="omid" src="https://user-images.githubusercontent.com/546931/116578411-abfdb080-a911-11eb-9c93-20b6c1fa7b43.png">

**Comment by srijithnair** [comment] 2021-05-03 14:21
Thanks @danielerne - we will be in touch with you through our services team, to troubleshoot further.

**Comment by ppuviarasu** [comment] 2021-08-19 16:28
Hi @danielerne,
Wanted to followup on this issue with OMID. Did you get a chance to update to the latest SDK & test if the issue is resolved.
If it helps we have upgraded to the latest OMSDK (1.3) on our SDK in v7.15. With the upgrade we are not able to see the lag when scrolling the view or heavy stack trace. If you are able to confirm the same then we can close this issue

**Comment by Daniel-Berger** [comment] 2022-02-07 20:15
We made further enhancements to how we interact with the OMID SDK in our release 7.20. Please review [our docs](https://docs.xandr.com/bundle/mobile-sdk/page/omid-friendly-obstruction-for-ios.html) for more details. I will close this ticket but please let us know if this issue persists.

**Closed** 2022-02-16 16:27 UTC
