### ISSUE TITLE
Our users are complaining about hanging of the ad banner.

### ISSUE THREAD

**Issue by s-hintz** [appnexus/mobile-sdk-ios#56] opened 2020-10-27 11:53 UTC
I can take about 10 seconds for the app to continue after loading the advertising.

**Comment by srijithnair** [comment] 2020-10-27 13:28
thanks, @s-hintz - what version of the SDK are you using?

**Comment by s-hintz** [comment] 2020-10-27 14:08
7.5

**Comment by s-hintz** [comment] 2020-10-27 15:34
I can reproduce the problem when I set the iPhone 11 to "low latency DNS" in the developer settings.
After swiping through about 20 articles the app gets slow. After about 60 it gets unusable slow.
The reason seems to be the web view.
Because when I enable another web view from another SDK it gets slow at about 10 articles.

**Comment by s-hintz** [comment] 2020-10-27 15:37
Do you ofter an SDK without web views?
Before we used AppNexus we used SmartAd which gave us an image URL and a link URL for each adverting. So we could display it natively without web views. That worked very well.

**Comment by ppuviarasu** [comment] 2020-10-27 16:15
hey stefan,

Did you see a sharp change in speed between v7.4 & v7.5?

Can you upgrade to the latest 7.7 & let us know if you are still seeing the slowness? 

To your question about SDK without webviews, waht adFormat are you using? for native ads we dont use webviews. as started we provided the url for the image content that the publisher can load himself. For all other adTypes we do render them on webviews.

**Comment by s-hintz** [comment] 2020-10-28 07:42
We never used v7.4.
We updated from v5.1.1 which was copied into our project to v7.5 which is integrated with Carthage.

We are using `ANBannerAdView` and `loadAd`.

We are using these formats:

	// Stages
	// Reminder / Superbanner - after navigation bar
    case banner = "banner"
    case superBanner = "superbanner"

	// ContentAd / ContentBar - after A-Teaser
	case mrec = "mrec"
    case billboard = "billboard"

	// ContentAd / ContentBar - where FAN was
	case mrecBTF = "mrec_btf"
    case billboardBTF = "billboard_btf"
    
    // Understitial
    case understitialBanner = "understitial"

**Comment by s-hintz** [comment] 2020-10-28 11:09
The `OMIDAppnexusAdSessionRegistry` holds strong references in `_activeAdSessions` which prevents the `ANWebView` from releasing after our article controllers are closed.
So the web views pile up in memory and slow down the device.

**Comment by s-hintz** [comment] 2020-10-28 14:05
With version 5.1.1 we had no speed issues with low latency DNS.
So we see a sharp change from 5.1.1 to 7.5.

**Comment by s-hintz** [comment] 2020-10-28 15:55
I see no performance difference between 7.5 and 7.7.

**Comment by s-hintz** [comment] 2020-10-30 09:00
Our QA found out that the problem is related to iOS 14.
With iOS 13 it works OK. And we have only complaints from iOS 14 users.

**Comment by s-hintz** [comment] 2020-12-11 10:48
Do we get an answer from AppNexus this year?

**Comment by ppuviarasu** [comment] 2020-12-11 14:53
Hey Stephen,
Can you create a ticket for us to work on the same. v5.1 to 7 is a big step & new measurement SDK's have been included which could be the cause. again not sure why it works on iOS 13 & not 14.
Try disabling OMID SDK & test to see if you see the slowness. 
`ANSDKSettings.sharedInstance.enableOpenMeasurement = FALSE;`

Create a ticket & give details about the placement and integration details for us to prioritize and look into this.

Regards
Punnaghai

**Comment by s-hintz** [comment] 2020-12-11 15:06
What is this OMID SDK?

We are currently using the AppNexus SDK 7.7.
I added already details of our placements to this ticket on 28 Oct.

**Comment by s-hintz** [comment] 2020-12-11 15:09
To be able to compile, I had to write:

`ANSDKSettings.sharedInstance().enableOpenMeasurement = false`

**Comment by s-hintz** [comment] 2020-12-11 15:35
I can not tell that this line does change the performance.

Currently I do not see advertising in our article pages.
Banners are not shown and the mrec opens empty white.

![Simulator Screen Shot - iPhone 11 - 2020-12-11 at 16 31 05](https://user-images.githubusercontent.com/39526001/101922741-c4716680-3bce-11eb-8d4f-89dc438df336.png)

**Comment by ppuviarasu** [comment] 2020-12-11 16:47
From Oct 28th, i see this

`// Stages
// Reminder / Superbanner - after navigation bar
case banner = "banner"
case superBanner = "superbanner"

// ContentAd / ContentBar - after A-Teaser
case mrec = "mrec"
case billboard = "billboard"

// ContentAd / ContentBar - where FAN was
case mrecBTF = "mrec_btf"
case billboardBTF = "billboard_btf"

// Understitial
case understitialBanner = "understitial"`

I dont know which is the placement & whats the size.
Please provide them for testing & reproducing at our end.
Also please do create a case ticket for the same

**Comment by s-hintz** [comment] 2020-12-14 07:42
//      banner:         			320x50, 320x75, 320x160, 300x150
				//      superbanner:    			728x90
				//      mrec, mrec_btf:				300x250, 300x300
				//      billboard, billboard_btf:	800x250, 970x250

**Comment by srijithnair** [comment] 2020-12-15 03:28
Hi @s-hintz - we discussed this with our colleagues in the services team. Per their understanding this is caused by something extraneous to the SDK. You should hear from them soon - we will keep this ticket open till then.

**Comment by srijithnair** [comment] 2020-12-15 15:23
Closing this ticket - based on inputs from our colleagues in the Services team. Will review and escalate https://github.com/appnexus/mobile-sdk-ios/issues/57 with IAB.

**Closed by srijithnair** 2020-12-15 15:23 UTC
